services:
  app:
    build: .
    container_name: rh_app_teste
    ports:
      - "5000:5000"
    volumes:
      # Mapeia a pasta de documentos gerados para o seu Windows
      - ./generated_docs:/app/generated_docs
      # Mapeia o banco de dados para não perder dados ao reiniciar
      - ./log.db:/app/log.db
    environment:
      - FLASK_ENV=development